// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlDIYoSZBRVKLkgE_3jzBl4E0nL9LC7fo',
    appId: '1:740520582813:web:06943a33528c5a485ebe74',
    messagingSenderId: '740520582813',
    projectId: 'food-delivery-df362',
    authDomain: 'food-delivery-df362.firebaseapp.com',
    storageBucket: 'food-delivery-df362.appspot.com',
    measurementId: 'G-TZTQRGTVK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzcH7ByvnQz9lgCGwiaBN4biJZxa_JO_U',
    appId: '1:740520582813:android:76fa0211d5f5ebc55ebe74',
    messagingSenderId: '740520582813',
    projectId: 'food-delivery-df362',
    storageBucket: 'food-delivery-df362.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0iivs8KQySKwXwo0ncSPeD2ybWDuQKOA',
    appId: '1:740520582813:ios:fbfa4c68bf49c90e5ebe74',
    messagingSenderId: '740520582813',
    projectId: 'food-delivery-df362',
    storageBucket: 'food-delivery-df362.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0iivs8KQySKwXwo0ncSPeD2ybWDuQKOA',
    appId: '1:740520582813:ios:9412e793967ea9f75ebe74',
    messagingSenderId: '740520582813',
    projectId: 'food-delivery-df362',
    storageBucket: 'food-delivery-df362.appspot.com',
    iosBundleId: 'com.example.foodDelivery.RunnerTests',
  );
}
